# This will be the first part of the title tag for your site <title> site.name </title>
# ===============
name: "MRMRS"

# Populates the meta description for the site. Should be under 150 characters for best SEO purposes.
# ===============
descripiton: "Adam Morse is a designer / developer focused on readability, responsive interfaces, and client-side performance. User advocate. Vim evangelist."

# Owner (organization or individual) of site content
# ===============
author: "mrmrs"

#url: "[http:// ]"
# Chance this when you generate your site for production to your production URL i.e http://mrsjxn.com
# ===============
#url: "http://localhost:4000"
url: "http://mrmrs.cc"

# Publish future posts or not option. 
# ===============
future: false

# List files and directories to include. Dot files are excluded by default - so those are good to include here. Most things are added by
# default. I generally add my .htaccess file and nothing else.
# ===============
#include: .htaccess

# "A list of directories (including trailing slash) and files to exclude from the conversion"
# I normally exclude _sass, README*, and .gitignore
# Directories that start with an underscore _ are not copied over by default. Still like to include _sass anyways.
# ===============
exclude: [.gitignore, README.md]

# Style of permalinks
# ===============
permalink: pretty
